volumes:
  db-postgres-data:

services:
  db-postgres:
    image: {{ db_postgres_image }}
    init: true
    pids_limit: {{ core_pids_limit }}
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - FOWNER
      - SETGID
      - SETUID
    runtime: {{ runtime }}
    read_only: true
    networks:
      isolated_net:
        ipv4_address: {{ db_postgres_ip }}
    env_file:
      - "{{ instance_dir }}/.sandbox.env"
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DB}
    tmpfs:
      - /var/run/postgresql
      - /tmp:noexec,nosuid,nodev
      - /var/tmp:noexec,nosuid,nodev
    volumes:
      - db-postgres-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${PG_USER} -d ${PG_DB} || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 3
    restart: unless-stopped