"""Instance scaffolding: directory tree, sandbox.toml, env file, ACLs, secret prompting.

Implements the SCAFFOLD SUB-SEQUENCE (S1-S7) from the orchestrator design.
Called on first `sandbox start` for a project directory.
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
from typing import TYPE_CHECKING

from core.crypto import generate_credential
from core.hydration import IMAGE_REGISTRY

if TYPE_CHECKING:
    from pathlib import Path


def ensure_per_user_tree(home: Path) -> None:
    """Create ``<home>/``, ``<home>/config/``, ``<home>/state/`` with mode 0700.

    Idempotent: ``exist_ok=True`` suppresses ``FileExistsError`` and does NOT
    modify the mode of any pre-existing directory.
    """
    os.makedirs(home, mode=0o700, exist_ok=True)
    os.makedirs(home / "config", mode=0o700, exist_ok=True)
    os.makedirs(home / "state", mode=0o700, exist_ok=True)


def ensure_registry_seed(home: Path) -> None:
    """Create an empty ``<home>/state/instances.json`` if it does not exist.

    The presence of this file is the per-user-tree initialization signal
    consumed by lifecycle commands.
    """
    registry_path = home / "state" / "instances.json"
    if not registry_path.exists():
        registry_path.write_text(json.dumps({}))

if TYPE_CHECKING:
    from collections.abc import Callable, Sequence

# ─── S1: Directory Tree ──────────────────────────────────────────────────────

INSTANCE_SUBDIRS = [
    "docker/core",
    "docker/admin",
    "docker/extras",
    "docker/coredns",
    "config/admin",
    "config/core",
    "config/coredns",
    "config/dnsdist",
    "config/proxy",
    "log/admin",
    "log/core",
    "log/proxy",
    "log/orchestrator",
    "cache/core/.claude",
    "cache/admin/tmux_resurrect",
    "custom/config/admin",
    "custom/config/core",
    "secrets",
]


def create_instance_dirs(instance_dir: str) -> None:
    """Create the full instance directory tree. Idempotent."""
    for subdir in INSTANCE_SUBDIRS:
        os.makedirs(os.path.join(instance_dir, subdir), exist_ok=True)


# ─── S2: sandbox.toml ────────────────────────────────────────────────────────

_SANDBOX_TOML_TEMPLATE = """\
# sandbox.toml
# Sandbox instance infrastructure configuration.
# Generated by: sandbox init

[instance]
name = "{name}"
user_project_root = "{user_project_root}"
host_uid = "{host_uid}"
warmup_prompt = ""

[core]
shm_size = "2gb"
pids_limit = 400
mem_limit = "8gb"
cpus = 4.0
base_image = "{core_base_image}"
base_distro_family = "wolfi"
git_user = "{git_user}"
git_email = "{git_email}"

[admin]
shm_size = "2gb"
pids_limit = 400
mem_limit = "8gb"
cpus = 4.0
base_image = "{admin_base_image}"
base_distro_family = "debian"

[runtimes]
python = true
typescript = true
rust = true
go = false

[runtimes.node]
version = "20.12.2"
nvm_version = "0.39.7"

[components]
mcp_firecrawl = false
mcp_puppeteer = false

[components.db_postgres]
enabled = true
expose_host_ports = [5432]
pg_user = "sandbox"
pg_db = "sandbox_db"
image = "{db_postgres_image}"

[components.ingress]
web_ports = [3000, 8080]

[proxy.whitelist]
domains = [
  ".github.com",
  ".githubusercontent.com",
  ".api.anthropic.com",
  ".npmjs.com",
  ".npmjs.org",
  ".pypi.org",
  ".pythonhosted.org",
  ".crates.io",
  ".rust-lang.org",
  ".golang.org",
  ".go.dev",
  ".debian.org",
  ".ubuntu.com",
]
read_only_domains = [
  ".pypi.org",
  ".pythonhosted.org",
  ".npmjs.com",
  ".npmjs.org",
  ".crates.io",
  ".rust-lang.org",
  ".golang.org",
  ".go.dev",
  ".debian.org",
  ".ubuntu.com",
]
"""


def write_sandbox_toml(
    instance_dir: str,
    instance_name: str,
    project_dir: str,
    git_user: str = "",
    git_email: str = "",
) -> None:
    """Write sandbox.toml with auto-derived defaults."""
    content = _SANDBOX_TOML_TEMPLATE.format(
        name=instance_name,
        user_project_root=os.path.abspath(project_dir),
        host_uid=str(os.getuid()),
        git_user=git_user,
        git_email=git_email,
        core_base_image=IMAGE_REGISTRY["wolfi_base"].pinned,
        admin_base_image=IMAGE_REGISTRY["debian_trixie"].pinned,
        db_postgres_image=IMAGE_REGISTRY["postgres"].pinned,
    )
    toml_path = os.path.join(instance_dir, "sandbox.toml")
    with open(toml_path, "w") as f:
        f.write(content)


def _detect_git_config() -> tuple[str, str]:
    """Auto-detect git user.name and user.email from global config.

    Returns (name, email). Falls back to ('', '') if git is not installed
    or config values are unset.
    """
    name = ""
    email = ""
    try:
        result = subprocess.run(
            ["git", "config", "--global", "user.name"],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            name = result.stdout.strip()

        result = subprocess.run(
            ["git", "config", "--global", "user.email"],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode == 0:
            email = result.stdout.strip()
    except FileNotFoundError:
        pass
    return name, email


# ─── S3: .sandbox.env ────────────────────────────────────────────────────────

_ENV_HEADER = """\
# .sandbox.env — STRICTLY UNTRACKED SECRETS

# ── Core Container ────────────────────────────────────────────────────────────
CORE_ANTHROPIC_API_KEY=""
CORE_GITHUB_TOKEN=""
"""

_ENV_POSTGRES_BLOCK = """
# ── Database ──────────────────────────────────────────────────────────────────
PG_USER="sandbox"
PG_PASSWORD=""
PG_DB="sandbox_db"
"""

_ENV_FIRECRAWL_BLOCK = """
# ── MCP: Firecrawl ────────────────────────────────────────────────────────────
FIRECRAWL_API_KEY=""
"""


def create_env_file(env_path: str, *, db_postgres: bool, mcp_firecrawl: bool) -> None:
    """Create .sandbox.env with mode 0600 via O_CREAT|O_EXCL. Raises FileExistsError on conflict.

    PG_PASSWORD is auto-generated via generate_credential() (secrets.token_urlsafe(32)).
    """
    content = _ENV_HEADER
    if db_postgres:
        pg_password = generate_credential()
        block = _ENV_POSTGRES_BLOCK.replace('PG_PASSWORD=""', f'PG_PASSWORD="{pg_password}"')
        content += block
    if mcp_firecrawl:
        content += _ENV_FIRECRAWL_BLOCK

    # O_EXCL ensures atomic exclusive creation — no race window between create and chmod
    fd = os.open(env_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        os.write(fd, content.encode("utf-8"))
    finally:
        os.close(fd)


# ─── S4: Default ACLs ────────────────────────────────────────────────────────


def apply_default_acls(instance_dir: str, user_project_root: str, dev_user: str) -> None:
    """Apply default ACLs so dev can read container-created files (D-39)."""
    for target in [
        os.path.join(instance_dir, "log/"),
        os.path.join(instance_dir, "cache/"),
        user_project_root,
    ]:
        subprocess.run(
            ["setfacl", "-d", "-m", f"u:{dev_user}:rwx", target],
            check=True,
        )


# ─── S6: Secret prompting ────────────────────────────────────────────────────


def prompt_secrets(
    env_path: str,
    required_secrets: Sequence[tuple[str, str]],
    prompt_func: Callable[[str], str],
) -> None:
    """Prompt for secrets interactively using the provided prompt_func.

    In non-TTY mode (e.g. CI), skips prompting and prints guidance
    directing the operator to populate the env file manually.
    """
    if not sys.stdin.isatty():
        print(f"Non-interactive mode: populate secrets in {env_path} before running 'sandbox start'.")
        return

    # Read current content
    with open(env_path) as f:
        content = f.read()

    # Prompt for each secret and replace empty values
    for secret_name, description in required_secrets:
        value = prompt_func(f"{secret_name} ({description}): ")
        content = content.replace(
            f'{secret_name}=""',
            f'{secret_name}="{value}"',
        )

    # Write back
    with open(env_path, "w") as f:
        f.write(content)


# ─── S7: .initialized sentinel ───────────────────────────────────────────────


def write_initialized_sentinel(instance_dir: str) -> None:
    """Write the .initialized sentinel file. Idempotent."""
    sentinel_path = os.path.join(instance_dir, ".initialized")
    with open(sentinel_path, "w") as f:
        f.write("")
