"""Instance scaffolding: directory tree, sandbox.toml, env file, ACLs, secret prompting.

Implements the SCAFFOLD SUB-SEQUENCE (S1–S7) from the orchestrator design.
Called on first `sandbox start` for a project directory.
"""

import getpass
import os
import subprocess
import sys
from typing import Sequence


# ─── S1: Directory Tree ──────────────────────────────────────────────────────

INSTANCE_SUBDIRS = [
    "docker/core",
    "docker/admin",
    "docker/extras",
    "config/admin",
    "config/core",
    "config/dns-sidecar",
    "config/proxy",
    "log/admin",
    "log/core",
    "log/proxy",
    "log/orchestrator",
    "cache/.claude",
    "custom/config/admin",
    "custom/config/core",
]


def create_instance_dirs(instance_dir: str) -> None:
    """Create the full instance directory tree. Idempotent."""
    for subdir in INSTANCE_SUBDIRS:
        os.makedirs(os.path.join(instance_dir, subdir), exist_ok=True)


# ─── S2: sandbox.toml ────────────────────────────────────────────────────────

_SANDBOX_TOML_TEMPLATE = """\
# sandbox.toml
# Sandbox instance infrastructure configuration.
# Generated by: sandbox start (first run in project directory)

[project]
name = "{name}"
user_project_root = "{user_project_root}"
host_unprivileged_user = "{host_unprivileged_user}"
host_uid = "{host_uid}"
warmup_prompt = ""

[core]
shm_size = "2gb"
pids_limit = 400
base_image = "cgr.dev/chainguard/wolfi-base:latest"
base_distro_family = "wolfi"
git_user = ""
git_email = ""

[admin]
shm_size = "2gb"
pids_limit = 400
base_image = "debian:trixie-slim"
base_distro_family = "debian"

[runtimes]
python = true
typescript = true
rust = true
go = false

[runtimes.node]
version = "20.12.2"
nvm_version = "0.39.7"

[components]
db_postgres = true
mcp_firecrawl = false
mcp_puppeteer = false

[components.db_postgres]
expose_host_ports = [5432]

[components.ingress]
web_ports = [3000, 8080]

[proxy.whitelist]
domains = [
  ".github.com",
  ".githubusercontent.com",
  ".api.anthropic.com",
  ".npmjs.com",
  ".npmjs.org",
  ".pypi.org",
  ".pythonhosted.org",
  ".crates.io",
  ".rust-lang.org",
  ".golang.org",
  ".go.dev",
  ".debian.org",
  ".ubuntu.com",
]
"""


def write_sandbox_toml(
    instance_dir: str,
    project_name: str,
    project_dir: str,
    host_unprivileged_user: str,
) -> None:
    """Write sandbox.toml with auto-derived defaults."""
    content = _SANDBOX_TOML_TEMPLATE.format(
        name=project_name,
        user_project_root=os.path.abspath(project_dir),
        host_unprivileged_user=host_unprivileged_user,
        host_uid=str(os.getuid()),
    )
    toml_path = os.path.join(instance_dir, "sandbox.toml")
    with open(toml_path, "w") as f:
        f.write(content)


# ─── S3: .sandbox.env ────────────────────────────────────────────────────────

_ENV_HEADER = """\
# .sandbox.env — STRICTLY UNTRACKED SECRETS

# ── Core Container ────────────────────────────────────────────────────────────
CORE_ANTHROPIC_API_KEY=""
CORE_GITHUB_TOKEN=""
"""

_ENV_POSTGRES_BLOCK = """
# ── Database ──────────────────────────────────────────────────────────────────
PG_USER="agent"
PG_PASSWORD=""
PG_DB="sandbox_db"
"""

_ENV_FIRECRAWL_BLOCK = """
# ── MCP: Firecrawl ────────────────────────────────────────────────────────────
FIRECRAWL_API_KEY=""
"""


def create_env_file(
    env_path: str, *, db_postgres: bool, mcp_firecrawl: bool
) -> None:
    """Create .sandbox.env with mode 0600 via O_CREAT|O_EXCL. Raises FileExistsError on conflict."""
    content = _ENV_HEADER
    if db_postgres:
        content += _ENV_POSTGRES_BLOCK
    if mcp_firecrawl:
        content += _ENV_FIRECRAWL_BLOCK

    # O_EXCL ensures atomic exclusive creation — no race window between create and chmod
    fd = os.open(env_path, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    try:
        os.write(fd, content.encode("utf-8"))
    finally:
        os.close(fd)


# ─── S4: Default ACLs ────────────────────────────────────────────────────────


def apply_default_acls(
    instance_dir: str, user_project_root: str, dev_user: str
) -> None:
    """Apply default ACLs so dev can read container-created files (D-39)."""
    for target in [
        os.path.join(instance_dir, "log/"),
        os.path.join(instance_dir, "cache/"),
        user_project_root,
    ]:
        subprocess.run(
            ["setfacl", "-d", "-m", f"u:{dev_user}:rwx", target],
            check=True,
        )


# ─── S6: Secret prompting ────────────────────────────────────────────────────


def prompt_secrets(
    env_path: str,
    required_secrets: Sequence[tuple[str, str]],
) -> None:
    """Prompt for secrets interactively via getpass(). Raises RuntimeError if no TTY."""
    if not sys.stdin.isatty():
        raise RuntimeError(
            f"Sandbox initialized. Populate .sandbox.env at {env_path} and rerun."
        )

    # Read current content
    with open(env_path) as f:
        content = f.read()

    # Prompt for each secret and replace empty values
    for secret_name, description in required_secrets:
        value = getpass.getpass(f"{secret_name} ({description}): ")
        content = content.replace(
            f'{secret_name}=""',
            f'{secret_name}="{value}"',
        )

    # Write back
    with open(env_path, "w") as f:
        f.write(content)


# ─── S7: .initialized sentinel ───────────────────────────────────────────────


def write_initialized_sentinel(instance_dir: str) -> None:
    """Write the .initialized sentinel file. Idempotent."""
    sentinel_path = os.path.join(instance_dir, ".initialized")
    with open(sentinel_path, "w") as f:
        f.write("")
