# Copyright (c) 2026 zerotrust-ai. SPDX-License-Identifier: AGPL-3.0-or-later
# syntax=docker/dockerfile:1
ARG GOLANG_BASE
FROM ${GOLANG_BASE} AS build
WORKDIR /src
COPY fwd.go /src/fwd.go
RUN CGO_ENABLED=0 go build -ldflags="-s -w" -o /fwd /src/fwd.go

FROM scratch
COPY --from=build /fwd /fwd
USER 65534:65534
ENTRYPOINT ["/fwd"]
