"""L3 — privilege-boundary rule: sudoers (or polkit) drop-in install + probe.

L3 is the **last mutation phase of the base ceremony** and the only phase that
installs or mutates the privilege-boundary rule (spec "Phase Execution Order").
It runs as ROOT (the drop-in is root-owned mode 0440 / 0644); its
``depends_on`` is ``("l7",)`` so the dispatcher binary the rule pins already
exists on disk by the time the rule is written.

Content-aware probe (design D10): the *expected* rule body is rendered from the
current ``core.dispatch.Op`` enum + the resolved operator + the host's
``hostname`` + ``[host].docker_unprivileged_user`` + the L0-resolved
``MACHINECTL_PATH`` (re-resolved here via
:func:`core.setup.l0_identity.resolve_machinectl_path` — orchestrator decision
1; the phase-runner has no context bus, so re-resolution at render time IS the
L0↔live reconciliation and also catches a ``secure_path`` drift between L0 and
L3). The rendered bytes are byte-compared against the on-disk drop-in:

- absent drop-in → ``MISSING`` (act stages + ``visudo -cf`` + installs);
- present but byte-different (e.g. the Op enum grew on a wheel upgrade so the
  drop-in's inlined ``Cmnd_Spec`` enumeration is stale) → ``DRIFT`` (act
  re-renders + re-installs);
- present and byte-identical → ``ALREADY_CORRECT``.

Two load-bearing F-004 / B-3 invariants:

- The Cmnd_Spec path is the L0-resolved ``MACHINECTL_PATH``, NEVER a hardcoded
  ``/usr/bin/machinectl`` (B-3 — ``machinectl_cmd()`` emits *relative*
  ``machinectl``; sudo bridges relative→absolute via ``secure_path``; the rule
  is only correct if its Cmnd_Spec path equals that resolution).
- ZERO ``"`` characters appear in any ``Cmnd_Spec`` body (F-004 — sudoers
  ``Cmnd_Spec`` args use backslash-escape, not shell-quoting; a ``"`` passes
  ``visudo -cf`` but matches nothing at runtime). The renderer asserts this at
  render time, BEFORE ``visudo -cf`` is ever invoked, and additionally rejects
  any op-name segment not matching ``[a-z0-9-]+``.

The L3a per-op probe (the sister ``l3a_per_op_probe`` phase) is the *sufficient*
correctness signal; ``visudo -cf`` acceptance is necessary but not sufficient
(F-004's silent failure mode). L3's ``rollback`` removes the just-installed
drop-in so a failure between L3's act and L3a's sweep does not leave a
half-written grant on disk (idempotent ``rm``).
"""

from __future__ import annotations

import re
import socket
import subprocess
from pathlib import Path
from typing import TYPE_CHECKING

# ``_DISPATCH_BINARY`` is the single source of truth for the dispatcher path
# the rule pins inside the bash command argv slot; ``Op`` is the single source
# of truth for the enumerated ops (do not duplicate either literal).
from core.dispatch import _DISPATCH_BINARY, Op
from core.host_config import MachinectlAuth
from core.setup.l0_identity import resolve_machinectl_path
from core.setup.phase_runner import Identity, Phase, PhaseResult

if TYPE_CHECKING:
    from core.host_config import HostConfig
    from core.setup.phase_runner import SetupContext

# Owned drop-in paths (spec "Reserved Namespace File Ownership").
_SUDOERS_DIR = Path("/etc/sudoers.d")
_POLKIT_RULE_PATH = Path("/etc/polkit-1/rules.d/49-sandbox-ai-machinectl.rules")

# A managed-file header so an operator who opens the drop-in sees it is
# regenerated by setup and any hand-edit is lost on re-run (design risk note).
_SUDOERS_HEADER = "# sandbox-ai managed — do not edit; rerun 'sudo sandbox setup'"
_POLKIT_HEADER = "// sandbox-ai managed — do not edit; rerun 'sudo sandbox setup'"

# Op-name shape gate (spec "Op names rendered into the rule body MUST match
# [a-z0-9-]+"): visudo -cf is a syntactic gate, NOT a content gate — it
# silently accepts an op-name pattern containing ``*`` or ``'``. Reject any
# non-conforming op name at render time, before visudo.
_OP_NAME_RE = re.compile(r"^[a-z0-9-]+$")

# The no-arg ops (their Cmnd_Spec omits the trailing ``\ *`` so sudo denies
# arg-smuggling at the sudoers layer — V9 B7). Keyed on the *wire name* (not
# the enum member) so the membership test is independent of which iterable the
# renderer walks; an op the dispatcher would accept args for defaults to the
# arg-bearing ``\ *`` shape (the safe direction). Derived from the canonical
# ``Op`` enum so a wire-name rename there is a single-point change here.
_NO_ARG_OP_NAMES: frozenset[str] = frozenset(
    {Op.AUTH_PROBE.value, Op.COMPOSE_LS.value, Op.DOCKER_VERSION.value}
)


class RuleRenderError(ValueError):
    """The rendered rule body violates a load-bearing F-004 / B-3 invariant.

    Raised at render time — BEFORE the staged file is written or ``visudo -cf``
    is invoked — when an op name is not ``[a-z0-9-]+`` or any ``Cmnd_Spec``
    body would contain a ``"`` character (the F-004 silent-footgun shape).
    """


def _hostname() -> str:
    """The host's name, embedded verbatim into the rule's host clause."""
    return socket.gethostname()


def _cmnd_specs(machinectl_path: str, sandbox_user: str, op: Op) -> list[str]:
    """Render the ``Cmnd_Spec`` line(s) for ``op`` in the V9-validated shape.

    Shape (full invocation prefix; backslash-escaped embedded whitespace; NO
    double-quotes — F-004):

        ``<MACHINECTL_PATH> shell <user>@.host /bin/bash -c <dispatch>\\ <op>[…]``

    Returns a list because no-arg ops need TWO exact specs:

    - **arg ops** → one spec ``…<dispatch>\\ <op>\\ *`` — the trailing ``\\ *``
      matches the op's runtime args AND the ``--check`` probe arg.
    - **no-arg ops** (``auth-probe``, ``compose-ls``, ``docker-version``) → two
      EXACT specs (no ``\\ *`` wildcard, so arg-smuggling stays denied — V9 B7):
      ``…<dispatch>\\ <op>`` (the operator's runtime invocation) AND
      ``…<dispatch>\\ <op>\\ --check`` (L3a's per-op probe target — every op
      accepts ``--check`` as its no-op-success probe shape, so the rule must
      grant it; without this exact second spec the probe's ``<op> --check``
      can't match the bare ``<op>`` grant and L3a false-negatives — G2/F-016
      sibling, round-5 fedora: a password-operator's L3a got "password
      required" on ``auth-probe`` because the rule omitted the ``--check``
      shape). Granting the literal ``--check`` (no wildcard) is harmless: it is
      a no-op-success the orchestrator never emits at runtime.
    """
    op_name = op.value
    if _OP_NAME_RE.match(op_name) is None:
        raise RuleRenderError(
            f"op name {op_name!r} is not [a-z0-9-]+; refusing to render "
            f"(visudo -cf is a syntactic gate only — spec op-name rule)"
        )
    prefix = f"{machinectl_path} shell {sandbox_user}@.host /bin/bash -c"
    base = f"{_DISPATCH_BINARY}\\ {op_name}"
    if op_name not in _NO_ARG_OP_NAMES:
        return [f"{prefix} {base}\\ *"]
    return [f"{prefix} {base}", f"{prefix} {base}\\ --check"]


def render_sudoers_rule(
    machinectl_path: str, operator: str, hostname: str, sandbox_user: str
) -> str:
    """Render the full V9-validated sudoers drop-in body.

    Asserts the F-004 zero-``"`` invariant across every ``Cmnd_Spec`` body at
    render time — BEFORE the staged file is written and ``visudo -cf`` is
    invoked. Raises :class:`RuleRenderError` on any violation.
    """
    specs = [
        spec
        for op in Op
        for spec in _cmnd_specs(machinectl_path, sandbox_user, op)
    ]
    for spec in specs:
        if '"' in spec:
            raise RuleRenderError(
                f"rendered Cmnd_Spec contains a '\"' character (F-004 "
                f"silent-footgun shape; backslash-escape is required, never "
                f"shell-quoting): {spec!r}"
            )
    # Inline the Cmnd specs directly into the operator's user-spec — do NOT
    # define a shared ``Cmnd_Alias``. Cmnd_Alias names share a single GLOBAL
    # namespace across all of ``/etc/sudoers.d/``, so a per-operator drop-in
    # that declared ``Cmnd_Alias SANDBOX_OPS`` collided with every other
    # operator's drop-in ("duplicate Cmnd_Alias" — F-020), breaking the
    # multi-operator-by-accumulation property and polluting every operator's
    # ``sudo`` stderr. Inlining is collision-proof: each operator's user-spec is
    # wholly independent. (Repeated ``Defaults fast_glob`` across drop-ins is
    # harmless — duplicate ``Defaults`` is not an error, unlike ``Cmnd_Alias``.)
    cmnd_list = ", \\\n    ".join(specs)
    return (
        f"{_SUDOERS_HEADER}\n"
        f"Defaults fast_glob\n"
        f"{operator} {hostname}=(root) NOPASSWD: NOSETENV: \\\n"
        f"    {cmnd_list}\n"
    )


def render_polkit_rule(operator: str, sandbox_user: str) -> str:
    """Render the action-level polkit rule (POLKIT auth mode).

    POLKIT narrowing is inherently *coarser* than SUDO (spec "Polkit Rule
    Shape"): ``org.freedesktop.machine1.shell`` does not expose the invoked
    argv, so the rule grants the action for the operator → sandbox-user at the
    action level; per-op narrowing lives only at the application layer
    (convention-meta-test-enforced). There is no ``"`` / op-name concern here
    (no ``Cmnd_Spec``); JS string literals are the polkit idiom.
    """
    return (
        f"{_POLKIT_HEADER}\n"
        f"polkit.addRule(function(action, subject) {{\n"
        f'    if (action.id == "org.freedesktop.machine1.shell" &&\n'
        f'        subject.user == "{operator}" &&\n'
        f'        action.lookup("user") == "{sandbox_user}") {{\n'
        f'        return polkit.Result.YES;\n'
        f"    }}\n"
        f"}});\n"
    )


def _sudoers_path(operator: str) -> Path:
    """The SUDO-mode drop-in path for ``operator``."""
    return _SUDOERS_DIR / f"sandbox-ai-machinectl-{operator}"


def _drop_in_path(host_config: HostConfig, operator: str) -> Path:
    """The owned drop-in path for the configured auth mode."""
    if host_config.host.machinectl_authentication == MachinectlAuth.SUDO:
        return _sudoers_path(operator)
    return _POLKIT_RULE_PATH


def _expected_body(host_config: HostConfig, operator: str) -> str:
    """Render the expected drop-in body for the configured auth mode."""
    sandbox_user = host_config.host.docker_unprivileged_user
    if host_config.host.machinectl_authentication == MachinectlAuth.SUDO:
        return render_sudoers_rule(
            resolve_machinectl_path(host_config),
            operator,
            _hostname(),
            sandbox_user,
        )
    return render_polkit_rule(operator, sandbox_user)


def _probe(ctx: SetupContext) -> tuple[PhaseResult, str]:
    """Content-aware probe: render expected body, byte-compare to on-disk."""
    operator = ctx.operator
    host_config = ctx.host_config
    path = _drop_in_path(host_config, operator)
    expected = _expected_body(host_config, operator)
    try:
        observed = path.read_text()
    except FileNotFoundError:
        return PhaseResult.MISSING, f"{path} absent; will render + install"
    if observed == expected:
        return PhaseResult.ALREADY_CORRECT, f"{path} matches current Op enum"
    return (
        PhaseResult.DRIFT,
        f"{path} differs from the expected rule (stale Op enumeration / "
        f"machinectl-path drift); will re-render + re-install",
    )


def _act(ctx: SetupContext) -> str:
    """Stage, ``visudo -cf`` (SUDO), then atomically install the drop-in.

    SUDO mode: stage to ``/tmp/sandbox-ai-machinectl-<operator>.staged``,
    validate with ``visudo -cf``, then ``install -m 0440 -o root -g root`` to
    the final path. POLKIT mode: no ``visudo`` (it is a JS rule, not sudoers);
    ``install -m 0644 -o root -g root``.
    """
    operator = ctx.operator
    host_config = ctx.host_config
    body = _expected_body(host_config, operator)
    final_path = _drop_in_path(host_config, operator)
    is_sudo = host_config.host.machinectl_authentication == MachinectlAuth.SUDO

    staged = Path(f"/tmp/sandbox-ai-machinectl-{operator}.staged")
    staged.write_text(body)
    if is_sudo:
        result = subprocess.run(
            ["visudo", "-cf", str(staged)],
            capture_output=True,
            text=True,
            check=False,
        )
        if result.returncode != 0:
            raise RuleRenderError(
                f"visudo -cf rejected the staged rule "
                f"(exit {result.returncode}); refusing to install: "
                f"{result.stdout}{result.stderr}"
            )
    mode = "0440" if is_sudo else "0644"
    subprocess.run(
        [
            "install",
            "-m",
            mode,
            "-o",
            "root",
            "-g",
            "root",
            str(staged),
            str(final_path),
        ],
        check=True,
    )
    return f"installed {final_path} (mode {mode}, validated)"


def _reverify(ctx: SetupContext) -> bool:
    """Confirm the on-disk drop-in is byte-identical to the expected body."""
    operator = ctx.operator
    host_config = ctx.host_config
    path = _drop_in_path(host_config, operator)
    try:
        return path.read_text() == _expected_body(host_config, operator)
    except FileNotFoundError:
        return False


def _rollback(ctx: SetupContext) -> None:
    """Remove the just-installed drop-in (idempotent ``rm``).

    Fired by the phase-runner when L3 fails before L3a's sweep would otherwise
    run. ``missing_ok=True`` so a rollback of a never-installed file is a
    no-op (idempotent — design D1).
    """
    _drop_in_path(ctx.host_config, ctx.operator).unlink(missing_ok=True)


PHASE = Phase(
    id="l3",
    name="privilege-boundary rule (sudoers/polkit drop-in)",
    identity=Identity.ROOT,
    probe=_probe,
    act=_act,
    reverify=_reverify,
    depends_on=("l7",),
    rollback=_rollback,
)
