# Copyright (c) 2026 Rafa Souza. SPDX-License-Identifier: AGPL-3.0-or-later
"""Shared fixtures for ``tests/unit/core/setup/``.

Provides ``assert_phase_content_aware`` — the mechanical enforcement of the
design-D10 content-aware probe contract (see
:class:`core.setup.phase_runner.Phase`). Every setup phase's probe MUST detect
that on-disk state has drifted from the *current source of truth* (a wheel
upgrade changed the expected sudoers rule / dispatcher binary / pin); a
file-exists-only probe is forbidden.

This is a **fixture**, not an importable helper, because the project's
convention meta-test (``tests/unit/test_conventions.py``) bans runtime imports
of helper functions from a ``conftest.py``. Later parallel milestones' per-phase
tests consume this fixture (they do not edit this file — it is created once
here).
"""

from __future__ import annotations

from collections.abc import Callable
from typing import TYPE_CHECKING

import pytest
from core.setup.phase_runner import PhaseResult

if TYPE_CHECKING:
    from core.setup.phase_runner import Phase, SetupContext

# The callable a consuming test receives. It takes the phase under test, a
# ``SetupContext``, and a ``make_stale`` callable that mutates the test world
# so the phase's owned on-disk state no longer matches the current source of
# truth. It asserts:
#   1. before ``make_stale()``  → probe returns ALREADY_CORRECT (the world was
#      set up to match current source);
#   2. after  ``make_stale()``  → probe returns DRIFT (NOT ALREADY_CORRECT) —
#      proving the probe compares content, not mere presence.
ContentAwareAssertion = Callable[
    ["Phase", "SetupContext", Callable[[], None]], None
]


def _assert_phase_content_aware(
    phase: Phase,
    ctx: SetupContext,
    make_stale: Callable[[], None],
) -> None:
    """Drive ``phase.probe`` across a correct→stale transition.

    ``make_stale`` is the phase-specific mutation that injects synthetic
    stale-content inputs (e.g. shrink the rendered sudoers Op set, swap the
    on-disk dispatcher binary's bytes, edit the pinned sha). The phase's probe
    MUST report ``ALREADY_CORRECT`` while the world matches current source and
    ``DRIFT`` once ``make_stale`` has run — never ``ALREADY_CORRECT`` after.
    """
    before_result, _ = phase.probe(ctx)
    assert before_result == PhaseResult.ALREADY_CORRECT, (
        f"phase {phase.id!r}: probe must report ALREADY_CORRECT when on-disk "
        f"state matches current source, got {before_result!r}"
    )
    make_stale()
    after_result, _ = phase.probe(ctx)
    assert after_result == PhaseResult.DRIFT, (
        f"phase {phase.id!r}: probe must report DRIFT (not "
        f"{PhaseResult.ALREADY_CORRECT!r}) when on-disk state no longer "
        f"matches current source (content-aware-probe contract, design D10); "
        f"got {after_result!r}"
    )


@pytest.fixture
def assert_phase_content_aware() -> ContentAwareAssertion:
    """Yield the content-aware-probe assertion (design D10 enforcement)."""
    return _assert_phase_content_aware
