######################################################################################################################################
# Use modern completion
######################################################################################################################################

zstyle :compinstall filename '~/.zshrc'
autoload -Uz compinit && compinit

######################################################################################################################################
# History
######################################################################################################################################

HISTSIZE=1000000
SAVEHIST=1000000
setopt appendhistory
setopt hist_ignore_all_dups
setopt hist_ignore_space

######################################################################################################################################
# Styles
######################################################################################################################################

zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors
zstyle ':completion:*' special-dirs true
zstyle ':completion:*' list-colors

######################################################################################################################################
# Plugins
######################################################################################################################################

source /usr/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/zsh-autosuggestions/zsh-autosuggestions.zsh
fpath=(/usr/share/zsh-completions/src $fpath)
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

######################################################################################################################################
# Aliases
######################################################################################################################################

# List
alias ls='eza --icons --color=always --group-directories-first'
alias ll='eza -alF --icons --color=always --group-directories-first'
alias la='eza -a --icons --color=always --group-directories-first'
alias l='eza -F --icons --color=always --group-directories-first'
alias l.='eza -a | egrep "^\."'
alias grep='grep --color=auto'

# Dirs
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
alias ......="cd ../../../../.."

export LANG=en_US.UTF-8
export LC_ALL=en_US.UTF-8
export OPENSPEC_TELEMETRY=0

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# gitmux
export PATH="~/.install/gitmux:$PATH"

######################################################################################################################################
# DO NOT EDIT THIS GENERATED FILE
# 
# This file is ephemerally generated by the Sandbox Orchestrator. Any changes will be destroyed on the next `sandbox start`.
# To safely override UI settings (like Starship or Gitmux) or add aliases, use the Native Hook below by editing:
# /workspace/.sandbox/custom/.zshrc
######################################################################################################################################

if [ -f "/workspace/.sandbox/custom/.zshrc" ]; then
    source "/workspace/.sandbox/custom/.zshrc"
fi

# Warmup prompt: if set, launch claude in non-interactive mode on first shell init
if [ -n "${SANDBOX_WARMUP_PROMPT:-}" ]; then
    claude -p "$SANDBOX_WARMUP_PROMPT" --dangerously-skip-permissions
    unset SANDBOX_WARMUP_PROMPT
fi

eval "$(starship init zsh)"